"""knowledge document and file schema

Revision ID: 41ef9067fd7f
Revises: 9ebec935c7ca
Create Date: 2026-06-09 10:51:00.584813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41ef9067fd7f'
down_revision: Union[str, None] = '9ebec935c7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_tag'))
    )
    op.create_index(op.f('ix_kb_tag_name'), 'kb_tag', ['name'], unique=True)
    op.create_table('kb_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'DEPARTMENT', 'PUBLIC', name='spacevisibility', native_enum=False), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name=op.f('fk_kb_space_created_by_sys_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['sys_department.id'], name=op.f('fk_kb_space_department_id_sys_department'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_space'))
    )
    op.create_index(op.f('ix_kb_space_code'), 'kb_space', ['code'], unique=True)
    op.create_index(op.f('ix_kb_space_department_id'), 'kb_space', ['department_id'], unique=False)
    op.create_table('kb_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_category.id'], name=op.f('fk_kb_category_parent_id_kb_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['kb_space.id'], name=op.f('fk_kb_category_space_id_kb_space'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_category')),
    sa.UniqueConstraint('space_id', 'parent_id', 'name', name='uq_category_sibling_name')
    )
    op.create_index(op.f('ix_kb_category_parent_id'), 'kb_category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_kb_category_space_id'), 'kb_category', ['space_id'], unique=False)
    op.create_table('kb_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'REJECTED', 'ARCHIVED', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['sys_user.id'], name=op.f('fk_kb_document_author_id_sys_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['kb_category.id'], name=op.f('fk_kb_document_category_id_kb_category'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['sys_user.id'], name=op.f('fk_kb_document_reviewer_id_sys_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['kb_space.id'], name=op.f('fk_kb_document_space_id_kb_space'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_document'))
    )
    op.create_index(op.f('ix_kb_document_category_id'), 'kb_document', ['category_id'], unique=False)
    op.create_index(op.f('ix_kb_document_is_deleted'), 'kb_document', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_kb_document_space_id'), 'kb_document', ['space_id'], unique=False)
    op.create_index(op.f('ix_kb_document_status'), 'kb_document', ['status'], unique=False)
    op.create_index(op.f('ix_kb_document_title'), 'kb_document', ['title'], unique=False)
    op.create_table('kb_document_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('object_name', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], name=op.f('fk_kb_document_file_document_id_kb_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sys_user.id'], name=op.f('fk_kb_document_file_uploaded_by_sys_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_document_file')),
    sa.UniqueConstraint('object_name', name=op.f('uq_kb_document_file_object_name'))
    )
    op.create_index(op.f('ix_kb_document_file_document_id'), 'kb_document_file', ['document_id'], unique=False)
    op.create_table('kb_document_tag',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], name=op.f('fk_kb_document_tag_document_id_kb_document'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['kb_tag.id'], name=op.f('fk_kb_document_tag_tag_id_kb_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id', name=op.f('pk_kb_document_tag'))
    )
    op.create_table('kb_document_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], name=op.f('fk_kb_document_version_created_by_sys_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['kb_document.id'], name=op.f('fk_kb_document_version_document_id_kb_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_document_version')),
    sa.UniqueConstraint('document_id', 'version_no', name='uq_document_version')
    )
    op.create_index(op.f('ix_kb_document_version_document_id'), 'kb_document_version', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_document_version_document_id'), table_name='kb_document_version')
    op.drop_table('kb_document_version')
    op.drop_table('kb_document_tag')
    op.drop_index(op.f('ix_kb_document_file_document_id'), table_name='kb_document_file')
    op.drop_table('kb_document_file')
    op.drop_index(op.f('ix_kb_document_title'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_status'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_space_id'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_is_deleted'), table_name='kb_document')
    op.drop_index(op.f('ix_kb_document_category_id'), table_name='kb_document')
    op.drop_table('kb_document')
    op.drop_index(op.f('ix_kb_category_space_id'), table_name='kb_category')
    op.drop_index(op.f('ix_kb_category_parent_id'), table_name='kb_category')
    op.drop_table('kb_category')
    op.drop_index(op.f('ix_kb_space_department_id'), table_name='kb_space')
    op.drop_index(op.f('ix_kb_space_code'), table_name='kb_space')
    op.drop_table('kb_space')
    op.drop_index(op.f('ix_kb_tag_name'), table_name='kb_tag')
    op.drop_table('kb_tag')
    # ### end Alembic commands ###

