"""initial identity and access schema

Revision ID: 9ebec935c7ca
Revises: 
Create Date: 2026-06-08 19:35:09.410630
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9ebec935c7ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_department.id'], name=op.f('fk_sys_department_parent_id_sys_department'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_department'))
    )
    op.create_index(op.f('ix_sys_department_parent_id'), 'sys_department', ['parent_id'], unique=False)
    op.create_table('sys_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_permission'))
    )
    op.create_index(op.f('ix_sys_permission_code'), 'sys_permission', ['code'], unique=True)
    op.create_table('sys_resource_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY', name='granteffect', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_resource_grant')),
    sa.UniqueConstraint('subject_type', 'subject_id', 'resource_type', 'resource_id', 'action', name='uq_resource_grant_scope')
    )
    op.create_index(op.f('ix_sys_resource_grant_resource_id'), 'sys_resource_grant', ['resource_id'], unique=False)
    op.create_index(op.f('ix_sys_resource_grant_resource_type'), 'sys_resource_grant', ['resource_type'], unique=False)
    op.create_index(op.f('ix_sys_resource_grant_subject_id'), 'sys_resource_grant', ['subject_id'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_role'))
    )
    op.create_index(op.f('ix_sys_role_code'), 'sys_role', ['code'], unique=True)
    op.create_table('sys_role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], name=op.f('fk_sys_role_permission_permission_id_sys_permission'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_role_permission_role_id_sys_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_sys_role_permission'))
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['sys_department.id'], name=op.f('fk_sys_user_department_id_sys_department'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_user'))
    )
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('sys_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_refresh_token_user_id_sys_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_refresh_token'))
    )
    op.create_index(op.f('ix_sys_refresh_token_token_hash'), 'sys_refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sys_refresh_token_user_id'), 'sys_refresh_token', ['user_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], name=op.f('fk_sys_user_role_role_id_sys_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name=op.f('fk_sys_user_role_user_id_sys_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_sys_user_role'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_refresh_token_user_id'), table_name='sys_refresh_token')
    op.drop_index(op.f('ix_sys_refresh_token_token_hash'), table_name='sys_refresh_token')
    op.drop_table('sys_refresh_token')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_role_code'), table_name='sys_role')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_resource_grant_subject_id'), table_name='sys_resource_grant')
    op.drop_index(op.f('ix_sys_resource_grant_resource_type'), table_name='sys_resource_grant')
    op.drop_index(op.f('ix_sys_resource_grant_resource_id'), table_name='sys_resource_grant')
    op.drop_table('sys_resource_grant')
    op.drop_index(op.f('ix_sys_permission_code'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_department_parent_id'), table_name='sys_department')
    op.drop_table('sys_department')
    # ### end Alembic commands ###

